services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    _instanceof:
        Symfony\Bundle\FrameworkBundle\Controller\AbstractController:
            calls:
                - [ setContainer, [ '@service_container' ] ]

    Pbdkn\SolarW5Bundle\:
        resource: ../../
        exclude: ../../{DependencyInjection,Resources,Model}
        
    Pbdkn\SolarW5Bundle\Controller\ContentElement\FE\FeSolarTestController:
        tags:
            - 
                name: contao.content_element 
                category: fe_solar_test_elements
        public: true
        
