services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $projectDir: '%kernel.project_dir%'

    Pbdkn\SolarW5Bundle\:
        resource: ../src/
        exclude: ../src/{DependencyInjection,Model}


